name: Develop Breaking Changes

on:
  pull_request:
    types: [assigned, opened, reopened, synchronize]
    branches: [develop]

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commit messages for breaking changes
        id: breaking_changes
        env:
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          # Function to check if breaking changes are present
          check_breaking_changes() {
            local commit=$1
            local breaking=$(git show --pretty="format:%b" --no-patch $commit | grep -F "BREAKING CHANGE")

            echo "Breaking: $breaking"

            if [[ "$breaking" == *"BREAKING CHANGE"* ]]; then
              echo "Commit $commit is a breaking change and cannot be merged into develop."
              exit 1
            fi

          }

          # Get all commits in the PR
          commits=$(git rev-list $BASE_SHA..$HEAD_SHA)

          # Iterate over all commits in the PR and verify each one
          for COMMIT in $commits; do
            check_breaking_changes $COMMIT
          done

          echo "No breaking changes detected."

  check-api-snapshot:
    name: Validate API snapshot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch (e.g. feat branch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for full branch context

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      # Build and snapshot current PR branch
      - name: Build PR declaration files
        run: yarn build:declaration-only

      - name: Generate PR API snapshot
        run: |
          yarn api-snapshot:generate
          mv api-snapshot.json pr-api-snapshot.json

      # # Checkout and build develop snapshot
      # - name: Stash changes
      #   run: git stash --include-untracked

      - name: Checkout develop branch
        run: git checkout origin/develop

      - name: Install dependencies (develop)
        run: yarn --frozen-lockfile

      - name: Build develop declaration files
        run: yarn build:declaration-only

      - name: Generate develop API snapshot
        run: |
          yarn api-snapshot:generate
          mv api-snapshot.json develop-api-snapshot.json

      # Compare snapshots: develop vs PR
      - name: Compare API snapshots
        run: |
          cp develop-api-snapshot.json base-api-snapshot.json
          cp pr-api-snapshot.json current-api-snapshot.json
          yarn api-snapshot:compare
